<!-- // Eror stop the execution but it not handle the syntax eror -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eror Try and Catch metod </title>
</head>
<body>
    

    <h2>Catch method did'nt work bt finally function work if it has eror too  </h2>

    <script>
        try{
           // this is our code 
           alert("Assalamualaikum EveryOne");
           alert(x);

           alert("Allah Hafez for Today See you NextDay");
        }catch(err){
      // its eror handeling part but not work if you have syntax Eror
      alert("this is inside catch block")
        }
        finally{
            alert("finally function work done if catch method has bugs  ");
        }
    </script>
</body>
</html>
